# Étape 1 : Utiliser une image de base contenant Node.js
FROM node:21.2.0 AS build

# Étape 2 : Définir le répertoire de travail
WORKDIR /

# Étape 3 : Copier les fichiers package.json et package-lock.json
COPY package.json package-lock.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier tous les autres fichiers
COPY . .

# Étape 6 : Construire l'application
RUN npm run build

# Étape 7 : Utiliser une image de base légère pour servir l'application
FROM nginx:alpine

# Étape 8 : Copier les fichiers construits à partir de l'étape précédente
COPY --from=build /app/build /usr/share/nginx/html

# Étape 9 : Exposer le port 80 pour que l'application puisse être accessible
EXPOSE 80

# Étape 10 : Commande de démarrage pour nginx
CMD ["nginx", "-g", "daemon off;"]
