# Utiliser une image de base contenant Node.js
FROM node:21.2.0

# Définir le répertoire de travail
WORKDIR /usr/src

# Copier le fichier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tous les fichiers du répertoire actuel vers le répertoire de travail dans le conteneur
COPY . .

# Exposer le port sur lequel l'application s'exécute
EXPOSE 3000

# Commande de démarrage de l'application
CMD ["node", "index.js"]
